trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: vscode-csharp
    trigger:
      tags:
      - auto-release

variables:
- group: VisualStudioMarketplace # Expected to provide VisualStudioMarketplacePAT (https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token)

jobs:
- job: release
  pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  steps:
  - checkout: none
  - pwsh: npm i -g vsce
    displayName: ⚙️ Install vsce
  - powershell: |
      $contentType = 'application/json';
      $headers = @{ Authorization = 'Bearer $(System.AccessToken)' };
      $rawRequest = @{ daysValid = 365 * 2; definitionId = $(resources.pipeline.CI.pipelineID); ownerId = 'User:$(Build.RequestedForId)'; protectPipeline = $false; runId = $(resources.pipeline.CI.runId) };
      $request = ConvertTo-Json @($rawRequest);
      Write-Host $request
      $uri = "$(System.CollectionUri)$(System.TeamProject)/_apis/build/retention/leases?api-version=6.0-preview.1";
      Invoke-RestMethod -uri $uri -method POST -Headers $headers -ContentType $contentType -Body $request;
    displayName: 🗻 Retain build

  # TODO - Modify github tags for released build.

  - download: CI
    artifact: package
    displayName: 🔻 Download package artifact
  - pwsh: | # Package publishing to pre-release https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
      $additionalPublishArgs = ,'publish'
      $ShippingBranch = '$(resources.pipeline.CI.sourceBranch)'
      Write-Host "Shipping branch: $ShippingBranch"
      if ($ShippingBranch -ne 'refs/heads/release') {
        $additionalPublishArgs += '--pre-release'
      }
      $additionalPublishArgs += '--packagePath'
      $additionalPublishArgs += Get-ChildItem *.vsix |% { $_.Name }
      Write-Host "##[command]vsce $additionalPublishArgs"
      if ('${{ parameters.DryRun }}' -eq 'true') {
        Write-Host "##vso[task.logissue type=warning]Marketplace publish skipped for dry run."
        exit 0
      }
      vsce @additionalPublishArgs
    displayName: 📦 Publish to Marketplace
    workingDirectory: $(Pipeline.Workspace)/CI/package
    env:
      VSCE_PAT: $(VisualStudioMarketplacePAT)
